name: Array API Tests (NumPy latest)

on: [push, pull_request]

jobs:
  array-api-tests-numpy-latest:
    uses: ./.github/workflows/array-api-tests.yml
    with:
      package-name: numpy
      python-versions: '[''3.10'', ''3.13'', ''3.14'']'
      pytest-extra-args: -n 4
      extra-env-vars: |
        ARRAY_API_TESTS_XFAIL_MARK=skip
